### ISSUE TITLE
Support fully Python 3.11

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio-pypi#6]
Currently, the Python version 11 is not fully supported because build fails with the following error:

```
Running pylint on PyPi sources.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/astroid/nodes/node_classes.py", line 49, in <module>
    from astroid import decorators, mixins, util
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/astroid/decorators.py", line 27, in <module>
    import wrapt
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/home/runner/work/zserio-pypi/zserio-pypi/build/test/wheel/pyenv/lib/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/inspect.py)
FATAL ERROR - Running pylint failed with return code 1!
```

**Comment by Mi-La** [comment]
Done in scope of #7 .
